config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
  namespace :user do
    get 'homes/top'
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :user do
    root to: "homes#top"
    get "about" => "homes#about", as: :about

    resources :posts, onry: [:index, :show, :create, :edit, :update, :destroy] do
      resources :comments, onry: [:create, :edit, :update, :destroy]
      resource :book_marks, only: [:create, :destroy]
    end
    resources :genres, onry: [:show]
    resources :tags, only: [:show]
    resources :users do
      member do
        get :book_marks
      end
    end
    get '/search', to: 'searches#search'
  end

  get "admin" => "admin/homes#top", as: :admin
  namespace :admin do
    resources :posts, onry: [:index, :show, :edit, :update, :destroy] do
      resources :comments, onry: [:destroy]
    end
    resources :genres, onry: [:create, :edit, :update, :destroy]
    resources :tags
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  validates :name, presence: true
  validates :account_name, presence: true

  def self.search_for(content, method)
    User.where('account_name LIKE ?', '%' + content + '%')
  end

#ゲストログイン
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com', account_name: 'guestuser') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :account_name, :email, :biography)
  end

end

app/controllers/user/book_marks_controller.rb
class User::BookMarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    book_mark = current_user.book_marks.new(post_id: @post.id)
    book_mark.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    book_mark = current_user.book_marks.find_by(post_id: @post.id)
    book_mark.destroy
  end

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    comment = @post.comments.find(params[:id])
    comment.destroy
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def ensure_current_user
    @comment = Comment.find(params[:id])
    if @comment.user_id != current_user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts")
    end
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @tags = Tag.all
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:create, :edit, :update, :destroy]
  before_action :ensure_current_user, {only: [:edit, :update]}

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tags = params[:post][:name].split(',')
    if @post.save
      @post.save_tags(tags)
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
    @genres = Genre.all
    @tags=Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    @tags = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])
    tags = params[:post][:name].split(',')
    if @post.update(post_params)
      @post.update_tags(tags)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.update_tags([])
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:genre_id, :user_id, :title, :text)
  end

  def ensure_current_user
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts")
    end
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Post.search_for(@content, @method)
		end
	end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
    @genres = Genre.all
    @tags = Tag.all
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  before_action :ensure_current_user, only: [:edit, :update, :book_marks]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def book_marks
    @user = User.find(params[:id])
    book_marks = BookMark.where(user_id: @user.id).pluck(:post_id)
    @book_mark_posts = Post.find(book_marks)
  end

  private

  def user_params
    params.require(:user).permit(:name, :account_name, :email, :biography)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:notice]="権限がありません"
      redirect_to("/posts")
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/book_marks_helper.rb
module User::BookMarksHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/views/user/users/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>ユーザー名</th>
          </tr>
        </thead>
        <% users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user, class: "user_#{user.id}" do %>
                  <%= user.account_name %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/user/users/book_marks.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>ブックマークした投稿一覧</h5>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>ジャンル</th>
            <th>本文</th>
          </tr>
        </thead>
        <% @book_mark_posts.reverse_each do |post|%>
          <tbody>
            <tr>
              <td>
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
              </td>
              <td><%= post.genre.name %></td>
              <td><%= post.text %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>情報編集</h5>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user, url: user_path do |f| %>
        <table class="table table-borderless">
          <tr>
            <td class="col-3">氏名</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td class="col-3">アカウント名</td></td>
            <td><%= f.text_field :account_name %></td>
          </tr>
          <tr>
            <td class="col-3">メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td class="col-3">自己紹介</td>
            <td><%= f.text_area :biography %></td>
          </tr>
          <tr>
            <td><%= f.submit "変更を保存", class: "btn btn-sm btn-success" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/index.html.erb
ユーザー一覧
<%= render 'index',users: @users %>

app/views/user/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><%= @user.account_name %>のマイページ</h4>
      <table class="table table-bordered">
        <% if current_user.id == @user.id %>
          <tr>
            <td class="table-active">名前</td>
            <td><%= @user.name %></td>
          </tr>
        <% end %>
        <tr>
          <td class="table-active">アカウント名</td>
          <td><%= @user.account_name %></td>
        </tr>
        <% if current_user.id == @user.id %>
          <tr>
            <td class="table-active">メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
        <% end %>
        <tr>
          <td class="table-active">自己紹介</td>
          <td><%= @user.biography %></td>
        </tr>
      </table>
    <% if @user.name != "guestuser" && @user.id == current_user.id %>
      <%= link_to '登録情報編集', edit_user_path, class: "btn btn-sm btn-success" %>
      <%= link_to "ブックマーク一覧", book_marks_user_path(@user), class: "btn btn-sm btn-primary" %>
    <% end %>
    </div>
  </div>
</div>